name: feature_extraction_pipeline
services:
  biopython_component:
    build:
      args: []
      context: C:\Users\denis\Desktop\fondant-component-issue\components\biopython_component
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "feature_extraction_pipeline",
      "run_id": "feature_extraction_pipeline-20240322164701", "component_id": "biopython_component",
      "cache_key": "f60f7ca40eb6fc7ae66724b7b7afcfb5"}'
    - --output_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/biopython_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Biopython component", "image": "biopython_component:latest",
      "description": "A component that uses Biopython to perform certain operations
      on sequences.", "consumes": {"sequence": {"type": "string"}}, "produces": {"sequence":
      {"type": "string"}, "molecular_weight": {"type": "float64"}}}, "consumes": {},
      "produces": {}}'
    - --input_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/checksum_component/manifest.json
    depends_on:
      checksum_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-component-issue\data:/data
  checksum_component:
    build:
      args: []
      context: C:\Users\denis\Desktop\fondant-component-issue\components\checksum_component
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "feature_extraction_pipeline",
      "run_id": "feature_extraction_pipeline-20240322164701", "component_id": "checksum_component",
      "cache_key": "2b1bce5dc6051579ef8bb096f075e6ac"}'
    - --output_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/checksum_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Checksum component", "image": "checksum_component:latest",
      "description": "Checksum component", "consumes": {"sequence": {"type": "string"}},
      "produces": {"sequence": {"type": "string"}, "sequence_checksum": {"type": "string"}}},
      "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/load_from_parquet/manifest.json
    depends_on:
      load_from_parquet:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-component-issue\data:/data
  load_from_parquet:
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "feature_extraction_pipeline",
      "run_id": "feature_extraction_pipeline-20240322164701", "component_id": "load_from_parquet",
      "cache_key": "e0f0788509d754d0430735f0f58ba677"}'
    - --output_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/load_from_parquet/manifest.json
    - --dataset_uri
    - /data/mock_data.parquet
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Load from parquet", "image": "fndnt/load_from_parquet:0.10.1",
      "description": "Component that loads a dataset from a parquet uri", "tags":
      ["Data loading"], "produces": {"additionalProperties": true}, "args": {"dataset_uri":
      {"description": "The remote path to the parquet file/folder containing the dataset",
      "type": "str"}, "column_name_mapping": {"description": "Mapping of the consumed
      dataset", "type": "dict", "default": {}}, "n_rows_to_load": {"description":
      "Optional argument that defines the number of rows to load. Useful for testing
      pipeline runs on a small scale", "type": "int", "default": "None"}, "index_column":
      {"description": "Column to set index to in the load component, if not specified
      a default globally unique index will be set", "type": "str", "default": "None"}}},
      "consumes": {}, "produces": {"sequence": {"type": "string"}}}'
    depends_on: {}
    entrypoint:
    - fondant
    - execute
    - main
    image: fndnt/load_from_parquet:0.10.1
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-component-issue\data:/data
  other_component:
    build:
      args: []
      context: C:\Users\denis\Desktop\fondant-component-issue\components\other_component
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "feature_extraction_pipeline",
      "run_id": "feature_extraction_pipeline-20240322164701", "component_id": "other_component",
      "cache_key": "4adfa9a1a9a223a3188b7e9baa06b1d0"}'
    - --output_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/other_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Other component", "image": "other_component:latest",
      "description": "Other component", "consumes": {"sequence": {"type": "string"},
      "sequence_checksum": {"type": "string"}}, "produces": {"sequence": {"type":
      "string"}, "sequence_length": {"type": "int64"}, "sequence_checksum": {"type":
      "string"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /.fondant/feature_extraction_pipeline/feature_extraction_pipeline-20240322164701/biopython_component/manifest.json
    depends_on:
      biopython_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-component-issue\data:/data
version: '3.8'
