name: test_pipeline
services:
  biopython_component:
    build:
      args: []
      context: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\components\biopython_component
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "test_pipeline", "run_id": "test_pipeline-20240415111731",
      "component_id": "biopython_component", "cache_key": "23c99c416c0dfb9cfa5bf273d713fff8"}'
    - --output_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/biopython_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Biopython component", "image": "biopython_component:latest",
      "description": "A component that uses Biopython to perform certain operations
      on sequences.", "consumes": {"sequence": {"type": "string"}}, "produces": {"molecular_weight":
      {"type": "float64"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/load_from_parquet/manifest.json
    depends_on:
      load_from_parquet:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\data:/data
  checksum_component:
    build:
      args: []
      context: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\components\checksum_component
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "test_pipeline", "run_id": "test_pipeline-20240415111731",
      "component_id": "checksum_component", "cache_key": "9a3c3d9cbfd44eb0dd8a6945a10190be"}'
    - --output_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/checksum_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Checksum component", "image": "checksum_component:latest",
      "description": "Checksum component", "consumes": {"sequence": {"type": "string"}},
      "produces": {"sequence_checksum": {"type": "string"}}}, "consumes": {}, "produces":
      {}}'
    - --input_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/biopython_component/manifest.json
    depends_on:
      biopython_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\data:/data
  load_from_parquet:
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "test_pipeline", "run_id": "test_pipeline-20240415111731",
      "component_id": "load_from_parquet", "cache_key": "e0f0788509d754d0430735f0f58ba677"}'
    - --output_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/load_from_parquet/manifest.json
    - --dataset_uri
    - /data/mock_data.parquet
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Load from parquet", "image": "fndnt/load_from_parquet:0.10.1",
      "description": "Component that loads a dataset from a parquet uri", "tags":
      ["Data loading"], "produces": {"additionalProperties": true}, "args": {"dataset_uri":
      {"description": "The remote path to the parquet file/folder containing the dataset",
      "type": "str"}, "column_name_mapping": {"description": "Mapping of the consumed
      dataset", "type": "dict", "default": {}}, "n_rows_to_load": {"description":
      "Optional argument that defines the number of rows to load. Useful for testing
      pipeline runs on a small scale", "type": "int", "default": "None"}, "index_column":
      {"description": "Column to set index to in the load component, if not specified
      a default globally unique index will be set", "type": "str", "default": "None"}}},
      "consumes": {}, "produces": {"sequence": {"type": "string"}}}'
    depends_on: {}
    entrypoint:
    - fondant
    - execute
    - main
    image: fndnt/load_from_parquet:0.10.1
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\data:/data
  write_to_file:
    command:
    - --metadata
    - '{"base_path": "/.fondant", "pipeline_name": "test_pipeline", "run_id": "test_pipeline-20240415111731",
      "component_id": "write_to_file", "cache_key": "9900393aba3316e87a598467fcd9f62a"}'
    - --output_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/write_to_file/manifest.json
    - --path
    - /data/export
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Write to file", "image": "fndnt/write_to_file:0.10.1",
      "description": "A Fondant component to write a dataset to file on a local machine
      or to a cloud storage bucket. The dataset can be written as csv or parquet.",
      "tags": ["Data writing"], "consumes": {"additionalProperties": true}, "args":
      {"path": {"description": "Path to store the dataset, whether it''s a local path
      or a cloud storage bucket,  must be specified. A separate filename will be generated
      for each partition. If you are using the local runner and export the data to
      a local directory,  ensure that you mount the path to the directory using the
      `--extra-volumes` argument.", "type": "str"}, "format": {"description": "Format
      for storing the dataframe can be either `csv` or `parquet`. As default  `parquet`
      is used. The CSV files contain the column as a header and use a comma as a delimiter.",
      "type": "str", "default": "parquet"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /.fondant/test_pipeline/test_pipeline-20240415111731/checksum_component/manifest.json
    depends_on:
      checksum_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    image: fndnt/write_to_file:0.10.1
    labels:
      pipeline_description: A pipeline to extract features from protein sequences.
    ports:
    - 8787:8787
    volumes:
    - source: C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\.fondant
      target: /.fondant
      type: bind
    - C:\Users\denis\Desktop\fondant-docker-issue\fondant-component-issue\data:/data
version: '3.8'
